[package]
name = "rust-postgres-crud"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
sqlx = { version = "0.7", features = ["postgres","runtime-tokio-rustls","macros","uuid","offline"]}
