[package]
name = "rust-postgres-crud"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
sqlx = { version = "0.8.6", default-features = false, features = [
  "postgres",
  "runtime-tokio-rustls",
  "macros",
  "uuid"
] }
tokio = { version = "1.48.0", features = ["full"] }

